# Generated by Django 2.2.2 on 2019-06-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
