# Generated by Django 2.2.2 on 2019-07-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_slider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='Index',
        ),
    ]
