# Generated by Django 2.2.2 on 2019-07-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190703_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='photo',
            field=models.ImageField(upload_to='photos/index/'),
        ),
    ]
