# Generated by Django 3.1.1 on 2020-09-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("is_published", models.BooleanField(default=False)),
                ("menu_slot", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "menuitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="menu.menuitem",
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(to="ingredients.PizzaIngredient"),
                ),
            ],
            bases=("menu.menuitem",),
        ),
        migrations.CreateModel(
            name="Burger",
            fields=[
                (
                    "menuitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="menu.menuitem",
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(to="ingredients.BurgerIngredient"),
                ),
            ],
            bases=("menu.menuitem",),
        ),
    ]
