# Generated by Django 2.2.2 on 2019-06-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('burgers', 'Burgers'), ('pasta', 'Pasta'), ('drinks', 'Drinks')], default='pizza', max_length=255),
        ),
    ]
